### ISSUE TITLE
TypeError in sound.py

### ISSUE THREAD

**Issue by logogin** [dholm/simpleguitk#3]
File "/usr/local/lib/python2.7/site-packages/simpleguitk/sound.py", line 62, in load_sound
    return Sound(URL)
  File "/usr/local/lib/python2.7/site-packages/simpleguitk/sound.py", line 22, in **init**
    self._sound = pygame.mixer.Sound(io.BytesIO(soundfile))
TypeError: Unrecognized argument (type _io.BytesIO)

I guess the problem is in line 22: 
`self._sound = pygame.mixer.Sound(io.BytesIO(soundfile))`
should be something like:
`self._sound = pygame.mixer.Sound(io.BytesIO(soundfile).read())`

pygame version 1.9.2a0 OSX 10.9.2

**Comment by dholm** [comment]
@PalmerX 
I tried it but it just generates an exception:

```Traceback (most recent call last):
  File "juicy_pong.py", line 61, in <module>
    bounce0 = load_sound("https://dl.dropboxusercontent.com/u/32888156/JuicyPong/Blip%20003.wav")
  File "../simpleguitk/simpleguitk/sound.py", line 62, in load_sound
    return Sound(URL)
  File "../simpleguitk/simpleguitk/sound.py", line 22, in __init__
    self._sound = pygame.mixer.Sound(file=io.BytesIO(soundfile))
TypeError: function takes exactly 1 argument (0 given)```

**Comment by Dinh-Hung-Tu** [comment]
Do anyone has an update on this? Thanks!

**Comment by dholm** [comment]
@Dinh-Hung-Tu Which version of pygame are you using?

**Comment by Dinh-Hung-Tu** [comment]
@dholm Hi David, I am using version `1.9.2`.

**Comment by dholm** [comment]
@Dinh-Hung-Tu Try using the HEAD version of simpleguitk and see if that resolves your issue.
